---
- name: Create user
  hosts:  localhost  #all hosts

  tasks:
    - name: create user
      user:
        name: jay
        groups: QA,DEV
        shell: /bin/bash


---
- name: Set Password
  hosts:  localhost  #all hosts

  tasks:
    - name: set password
      user:
        name: jay
        password: "{{ 'jay1234' | password_hash('sha512') }}"
        update_password: always



---
- name : remove user
  hosts: localhost  #all hosts

  tasks:
    - name: remove user
      user:
        name: jay
        state: absent
        remove : yes
        

