---
- name: Firewall Enable 
  hosts; localhost #all

  tasks:
    - name: firewall config
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: true

    - name: reload nginx
      service: 
        name: firewalld
        state: reloaded


  # firewall-cmd --get-services